# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba2d31bb3fece6c3712dbf6279d7b2db4b5c0d3c6e7302d39c8ed867d7ee342e3cea023bf9a7809a3271192da952aacf5f1c7d3968100c5b0875a996b8bd51aa

test:
  secret_key_base: 36f088de21b047ba707344d28cffd1fb77a0922dad10829e658641ba5ce550f6ee51ece10b2d31e72cf1aa8a529a8e1f496d16b9ed7cf5bea40b1c7cc7bfc274

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
